import { nanoid } from 'nanoid'

export const countries = [
  {
    id: nanoid(),
    name: 'Egypt',
    cities: [
      { id: '1', name: 'Cairo' },
      { id: '2', name: 'Giza' },
      { id: '3', name: 'Alexandria' },
      { id: '4', name: 'Dakahlia' },
      { id: '5', name: 'Red Sea' },
      { id: '6', name: 'Beheira' },
      { id: '7', name: 'Fayoum' },
      { id: '8', name: 'Gharbiya' },
      { id: '9', name: 'Ismailia' },
      { id: '10', name: 'Menofia' },
      { id: '11', name: 'Minya' },
      { id: '12', name: 'Qaliubiya' },
      { id: '13', name: 'New Valley' },
      { id: '14', name: 'Suez' },
      { id: '15', name: 'Aswan' },
      { id: '16', name: 'Assiut' },
      { id: '17', name: 'Beni Suef' },
      { id: '18', name: 'Port Said' },
      { id: '19', name: 'Damietta' },
      { id: '20', name: 'Sharkia' },
      { id: '21', name: 'South Sinai' },
      { id: '22', name: 'Kafr Al sheikh' },
      { id: '23', name: 'Matrouh' },
      { id: '24', name: 'Luxor' },
      { id: '25', name: 'Qena' },
      { id: '26', name: 'North Sinai' },
      { id: '27', name: 'Sohag' },
    ],
  },
  {
    id: nanoid(),
    name: 'Saudi Arabia',
    cities: [
      { id: nanoid(), name: 'Ar Riyad' },
      { id: nanoid(), name: 'Jeddah' },
      { id: nanoid(), name: 'Mecca' },
      { id: nanoid(), name: 'Medina' },
      { id: nanoid(), name: 'Ad Dammām' },
      { id: nanoid(), name: 'Tabūk' },
      { id: nanoid(), name: 'Al Hufūf' },
      { id: nanoid(), name: 'Al Qaţīf' },
      { id: nanoid(), name: 'Al Ḩillah' },
      { id: nanoid(), name: 'Aţ Ţā’if' },
      { id: nanoid(), name: 'Al Jubayl' },
      { id: nanoid(), name: 'Buraydah' },
      { id: nanoid(), name: 'Ḩafr al Bāţin' },
      { id: nanoid(), name: 'Yanbu' },
      { id: nanoid(), name: 'Ḩā’il' },
      { id: nanoid(), name: 'Abhā' },
      { id: nanoid(), name: 'Sakākā' },
      { id: nanoid(), name: 'Al Qurayyāt' },
      { id: nanoid(), name: 'Jāzān' },
      { id: nanoid(), name: 'Najrān' },
      { id: nanoid(), name: 'Al Wajh' },
      { id: nanoid(), name: 'Arar' },
      { id: nanoid(), name: 'Al Bāḩah' },
      { id: nanoid(), name: 'Tathlīth' },
    ],
  },
]
